
name: Deploy to Google Cloud

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    
     steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17.0.12'
    - name: Build with Maven
      run:
        mvn clean install --file ecomapp/pom.xml

    - uses: actions/checkout@v3

    - run: mkdir -p target/

    - run: echo hello > target/ecomapp-v1.jar

    - uses: actions/upload-artifact@v1
      with:
       name: ecomapp-v1
       path: target/

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker to use GCR
      run: |
        gcloud auth configure-docker gcr.io

      
  
    # --- Build & Push Backend (Java Microservices) Docker Image ---
    - name: Build & Push Backend Docker Image
      run: |
        docker build -t gcr.io/sincere-blade-452715-r7/myapp:latest -f ecomapp/Dockerfile .
        docker push gcr.io/sincere-blade-452715-r7/myapp:latest

    # --- Deploy to Kubernetes (GKE) ---
    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials my-cluster --zone us-central1-a

    - name: Deploy Backend Service
      run: |
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml


